Repository medik8s/node-maintenance-operator, pull requests merged in 2022-09, with the labels that each got.

#54 make OPERATOR_NS configurable
  hack/functest.sh
Labels: approved

#52 Tolerate control-plane node taint
  bundle/manifests/node-maintenance-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, ok-to-test

#53 Rename master -> control-plane and support control-plane node taint
  api/v1beta1/nodemaintenance_webhook.go
  api/v1beta1/nodemaintenance_webhook_test.go
  test/e2e/node_maintenance_test.go
Labels: approved, lgtm, ok-to-test

#56 Update Operator-sdk 1.23
  Makefile
  bundle.Dockerfile
  bundle/manifests/node-maintenance-operator.clusterserviceversion.yaml
  bundle/manifests/nodemaintenance.medik8s.io_nodemaintenances.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/nodemaintenance.medik8s.io_nodemaintenances.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: approved, lgtm

#57 Update Makefile's tools version & new target
  Makefile
  api/v1beta1/groupversion_info.go
Labels: approved, lgtm

#58 NMO in OperatorHub.io
  README.md
Labels: approved, lgtm
